
tasks:
  - init: make setup # runs during prebuild
    command: make start-bit

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - nrwl.angular-console