version: "3"

services:
  # strapi:
  #   container_name: strapi
  #   image: watheialabs/waweb-www
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_CLIENT=postgres
  #     - DATABASE_HOST=db
  #     - DATABASE_PORT=5432
  #     - DATABASE_NAME=strapi
  #     - DATABASE_USERNAME=strapi
  #     - DATABASE_PASSWORD=strapi
  #   ports:
  #     - 8080:4200
  #   depends_on:
  #     - db
  #   command: "strapi start"
  #   volumes:
  #   - ./app:/srv/app

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./prisma/.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
